version: '2'
services:
    skillassessmentapp-app:
        image: skillassessmentapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://skillassessmentapp-mysql:3306/skillassessmentapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 888:888
    skillassessmentapp-mysql:
        extends:
            file: mysql.yml
            service: skillassessmentapp-mysql
